heptiolabs/wardroom

packer/README.md
packer/packer.json

In order to facilitate some level of traceability, add some standard
tags to the AMI builds.

Add AMI tags to the AMI builds

---

ansible/roles/kubernetes-common/defaults/main.yml
ansible/roles/kubernetes-common/tasks/main.yml
ansible/roles/kubernetes-common/templates/etc/systemd/system/kubelet.service.d/09-extra-args.conf
ansible/roles/kubernetes-common/templates/etc/systemd/system/kubelet.service.d/09-vagrant.conf

The kubelet packages structure the systemd configs such that they may be
included lexically. As we would like to manipulate the flags passed to
the kubelet, provide a mechanism for that to happemn.

Add a generic mechanism for adding kubelet extra args

---

ansible/roles/common/defaults/main.yml
ansible/roles/common/tasks/debian.yml
ansible/roles/common/tasks/redhat.yml
packer/packer.json

Even though we try to keep the base AMI specifications current, it would
be a good idea to upgrade the packages during image build.  This will
ensure we pick up any packages that have not made it into the stock AMIs
yet.

Upgrade the base AMI's upon build

---

ansible/roles/kubernetes-master/tasks/main.yml
ansible/roles/kubernetes-node/tasks/main.yml
swizzle/provision.py
swizzle/swizzle.yml

This change adds a primary_master host group so that we are able to
rebuild from any combination of nodes. We delegate a node in from the
'masters' group the 'primary_master' and use it to bootstrap the others.
Update provision.py to randomly select a primary master from the group
of masters.

Introduce the "primary_master" group.

---

ansible/roles/kubernetes/defaults/main.yml
ansible/roles/kubernetes/tasks/debian.yml
ansible/roles/kubernetes/tasks/redhat.yml

hardcoding the repo keys and urls is unfriendly to those who may need to
modify these. so, move these to defaults, so that they may be overriden.
Addresses #34

Move hardcoded repo urls to defaults

---

ansible/roles/common/tasks/debian.yml
ansible/roles/common/tasks/redhat.yml

This adds `jq` and `nfs-client` to the base OS.
// Fixes #17 
Signed-off-by: Steve Sloka <steves@heptio.com>

Added nfs client and jq to default install

---

ansible/roles/kubernetes-cni/defaults/main.yml
ansible/roles/kubernetes-cni/tasks/calico.yml
ansible/roles/kubernetes-cni/tasks/flannel.yml
ansible/roles/kubernetes-cni/tasks/main.yml

As we would like to support flannel in some environments, add this as an
option to the swizzle playbooks.
Also add retries to the calicoctl download, as the default mirror seems
a bit flaky.

Add flannel as a CNI provider

---

ansible/roles/docker/defaults/main.yml
ansible/roles/docker/templates/etc/docker/daemon.json

By default there is no limit the size of a container log. Docker
supports limiting the log file to a particular size, and this change
simply enables this feature. Note that this is a truncate and not a
rotate.

Add log file limits to the Docker conifguration

---

ansible/roles/common/defaults/main.yml
ansible/roles/common/tasks/debian.yml
ansible/roles/common/tasks/redhat.yml

Instead of hardcoding the packages in the common tasks themselves, move
them to the defaults for the common role. This allows them to be
modified selectively during configuration.
Introduce the "extra" packages concept where users may include
additional packages over top of the reauired set.
Fix the install of EPEL to install the rpm from over the wire.

Move packages from the common tasks to defaults

---

ansible/roles/kube-ucarp-vip/defaults/main.yaml
ansible/roles/kube-ucarp-vip/templates/etc/kubernetes/manifests/kube-ucarp-vip.yaml

Even though this is meant for reference only, dont hardcode values into
the kub-ucarp-vip role. Make the values configurable parameters so that
they may be overidden.

Parameterize the kube-ucarp-vip role

---

packer/us-west-2.json

This PR adds a Packer variable file for the AWS us-west-2 region, allowing Wardroom to build AMIs in us-west-2 as well as us-east-1.

Add variable file for AWS us-west-2 region

---

ansible/roles/common/tasks/redhat.yml

Per #74, CentOS AMIs without this setting will intermittently fail when running `kubeadm`. This PR updates the "common" Ansible role to ensure that `net.bridge.bridge-nf-call-iptables` is correctly set to 1.
Closes #74.

Update common role to fix intermittent /proc/sys/net/bridge/bridge-nf-call-iptables errors

---

packer/README.md

This pull request adds information to `packer/README.md` with the minimum AWS IAM permissions required to run Wardroom and build AWS AMIs.
This PR partially addresses #45.

Update documentation with required permissions

---

packer/README.md

Update `packer/README.md` to include documentation on the GCP permissions required in order for Wardroom to function correctly when building GCP images.

Add GCP permissions to documentation

---

ansible/roles/docker/tasks/redhat.yml

Due to issues with some dependencies, Docker CE 17.03 installation on CentOS/RHEL 7 can't be accomplished using standard `yum` module. This PR fixes the installation by using a `command` module to run `yum` directly.
Addresses issue #72 (see conversation there for links to dependencies issues referenced above).

Fix Docker CE 17.03.x installation

---

ansible/playbook.yml
ansible/pre.yml

Right now we have the same code for installing python in two different
places. Additionally, this code assumes Debian based systems. So, clean
this up so that it only applies to Debian systems, and such that it is
consolidated in `pre.yml`

Make the python preinstall more DRY

---

ansible/pre.yml

This PR adds retries to the Debian-specific Python 2 installation pre-task. This helps address timeouts due to flaky cloud repositories that may not respond in a timely fashion.
This is related to PR #95.

Add retries to Python 2 pre-install task

---

packer/README.md
packer/oci-us-phoenix-1.json
packer/packer.json

This PR adds support for building Oracle Cloud Infrastructure (OCI) images via Wardroom. This PR makes the following changes:
1. Adds an "oracle-oci" builder to `packer.json`
2. Adds a variable file (`oci-us-phoenix-1.json`) that provides the base image OCID
3. Adds content to `packer/README.md` with instructions on building OCI images
For reliable image builds on OCI, a change to `ansible/playbook.yml` to add retries to the Debian/Ubuntu Python installation is needed; we believe this to be due to less-than-reliable `apt` mirrors hosted by Oracle. I'm holding those changes in a separate branch until #93 is resolved. Otherwise, this PR should be ready to merge.

Add support for building OCI images

---

ansible/roles/etcd/tasks/main.yml

The previous check for whether etcd had been downloaded was slightly
off. This change uses the proper registration state check.

Fix check for etcd being downloaded

---

swizzle/swizzle.yml

Etcd is running as a systemd service, so there's no need for docker or
kubernetes on the etcd nodes.

[swizzle] Don't install kubernetes packages on etcd nodes

---

ansible/roles/docker/defaults/main.yml
ansible/roles/docker/tasks/debian.yml
packer/aws-us-east-1.json
packer/aws-us-west-2.json
packer/packer.json

This PR returns Ubuntu 16.04 support to Wardroom. The `aws-us-east-1.json` and `aws-us-west-2.json` variable files have been updated to add an Ubuntu 16.04 AMI variable, and have been updated with `aws_region` to work around #123.
The Ansible `docker` role was updated to allow for different Docker versions on 16.04 versus 18.04.
These changes were tested by successfully building AMIs for both 16.04 and 18.04 with Kubernetes 1.11.7, 1.12.5, and 1.13.2 (all three versions on both 16.04 and 18.04). All builds completed successfully with no errors.

Add back Ubuntu 16.04 support

---

packer/packer.json

This PR changes the compute shape from VM.Standard1.1 to VM.Standard1.4, as the former is apparently no longer available on OCI (and thus causes Wardroom to fail when used to build OCI images).

Change compute shape

---

ansible/roles/packer-cleanup/tasks/main.yml

This PR add some Ansible tasks to the "packer-cleanup" role to remove extra /etc/hosts entries and clean up restrictive iptables rules. These clean-up tasks are primary targeting OCI builds. I tested these additional tasks against OCI (Ubuntu), AWS (Ubuntu), and AWS (CentOS), and saw no ill effects to the image build process as a result of adding them (nor were any ill effects observed in instances created on AWS with these changes in place). The changes _do_ work for OCI builds.

Add extra Packer cleanup tasks

---

packer/aws-us-east-2.json

This PR adds a variables file for the "us-east-2" region on AWS. The variables file properly sets the `aws_region` variable to workaround issue #123.

Add variables file for AWS us-east-2

---

packer/aws-us-east-2.json

This PR adds the value for Ubuntu 16.04 AMI ID to the variables file for us-east-2. Apparently this value was missed in PR #125.

Add Ubuntu 16.04 AMI to us-east-2 variables file

---

docs/README.md
docs/architecture.md

As a start to the effort to add documentation to Wardroom, this PR adds an architecture document that summarizes Wardroom's existing architecture.
Part of #130 (but does not fully close the issue).

Add files to start documentation

---

swizzle/Vagrantfile

This Vagrantfile is interpretting environment variables as strings and
not ints. Adjust so that the environment variable is cast to an int
before iterating.

Fix Vagrantfile environment variables

---

ansible/roles/docker/defaults/main.yml

Fixes #126 
Docker CE release notes: https://docs.docker.com/engine/release-notes/#18092
Docker v18.09.2 addresses a runc vulnerability (CVE-2019-5736).
Update the default docker version to a version >= v18.09.2

Update the default docker version to address runc vuln.

---

ansible/roles/common/tasks/debian.yml

ubuntu 16.04 needs a specific urllib3 version to work with `modify_manifest.py`
- tested on 1.13, would apply to all. 
```release-note
without this change the task for modify_manifest.py fails with the following
Traceback (most recent call last):
File "<stdin>", line 113, in <module>
File "<stdin>", line 105, in _ansiballz_main
File "<stdin>", line 48, in invoke_module
File "/tmp/ansible_modify_manifest_payload_QYXdeQ/__main__.py", line 19, in <module>
File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 58, in <module>
from . import utils
File "/usr/lib/python2.7/dist-packages/requests/utils.py", line 26, in <module>
from .compat import …
```

ubuntu 16.04 needs a specific version of urllib3

---

ansible/roles/docker/defaults/main.yml

Docker v18.09.2 addresses a runc vulnerability (CVE-2019-5736).
Update the default docker version to a version >= v18.09.2

Cherry-pick into 1.11.x: Update the default docker version to address runc vuln. (#150)

---

ansible/roles/docker/defaults/main.yml

Docker v18.09.2 addresses a runc vulnerability (CVE-2019-5736).
Update the default docker version to a version >= v18.09.2

Cherry-pick into 1.12.x: Update the default docker version to address runc vuln. (#150)

---

ansible/roles/docker/defaults/main.yml

Docker v18.09.2 addresses a runc vulnerability (CVE-2019-5736).
Update the default docker version to a version >= v18.09.2

Cherry-pick into v1.13.x: Update the default docker version to address runc vuln. (#150)

---

swizzle/examples/calico.yml

Signed-off-by: John Harris <joharris@vmware.com>
This PR adds the relevant NIC switch for virtualbox in the `examples/calico.yml` example.
Fixes #159 
- `1.` Master / all
N/A
```release-note
NONE
```

Add virtualbox support to calico example

---

ansible/roles/kubernetes-master/tasks/install.yml
swizzle/add-nodes.yml
swizzle/ansible.cfg
swizzle/install.yml
swizzle/main.yml
swizzle/provision.py

Break out the playbooks such that users can selectively run parts of the
code. In particular, the act of adding nodes should be pretty
lightweight. Whereas currently we run the whole playbook to add nodes,
this introduces an add-nodes.yml playbook so that users do not need to
touch the control plane nodes.

Make playbooks more composable

---

swizzle/add-nodes.yml

Kubeadm needs access to the kubeconfig file in
/etc/kubernetes/admin.conf. This file can only be used by a user with
elevated privileges.
Fixes #161

Become root when creating kubeadm token as part of add-nodes.yaml

---

ansible/roles/docker/tasks/debian.yml
ansible/roles/docker/tasks/main.yml
ansible/roles/kubernetes/tasks/main.yml

Fixes #119 
The docker-py python module is required to use the ansible docker_image
module. The docker_image module is used only when caching images on the
nodes.
With this change, docker-py is only installed on the nodes when actually
needed.

Conditionalize the installation of docker-py

---

ansible/roles/common/tasks/redhat.yml
ansible/roles/kubernetes-cni/tasks/flannel.yml
ansible/roles/kubernetes/tasks/main.yml

Fixes #99 
We were setting a sysctl net parameter in multiple places. Given that this is
always required, move this task to the 'kubernetes' role, which is
common to both the wardroom and swizzle.

Configure sysctl networking param in common role

---

Vagrantfile
ansible/roles/docker/defaults/main.yml

The ubuntu/xenial64 vagrant box only supports Virtualbox. Switch to generic/ubuntu1604
to support a wider range of Vagrant providers.
Additionally fixes up Docker installation on Xenial.
None
- `1.12 onwards`
_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._
```release-note
```

Xenial non virtualbox

---

ansible/roles/kubernetes-common/defaults/main.yml
ansible/roles/kubernetes-common/tasks/main.yml
ansible/roles/kubernetes-common/templates/etc/default/kubelet
ansible/roles/kubernetes-common/templates/etc/systemd/system/kubelet.service.d/09-extra-args.conf

With 1.11 the kubelet packages now support an external kubelet
environment file. Update the placement of this configuration from the
kubelet.d directory to the /etc/{default|sysconfig}/kubelet file.
Will cherry pick this change into the future branches as well.

Support kubelet environment file

---

ansible/roles/kubernetes-common/defaults/main.yml
swizzle/examples/calico.yml
swizzle/examples/canal.yml

Given that most environments should be able to leverage DNS to resolve
the common API server name, make the /etc/hosts management feature
opt-in.
Also update the existing provision.py example files to enable the
/etc/hosts management to avoid breaking them.
Fixes #165

Make the /etc/hosts management an opt-in feature

---

README.md
ansible/playbook.yml
docs/README.md
docs/bootstrapping-a-kubernetes-cluster.md
docs/building-images.md
packer/README.md
swizzle/README.md
swizzle/examples/calico.yml
swizzle/examples/canal.yml

This PR introduces additional documentation on how to use the swizzle functionality of wardroom.
In addition, it attempts to clarify the README with the goal of communicating that wardroom solves two things.
Fixes #130 
Given that we created a `docs/` directory, I have put all the user-facing documentation there. For example, you will notice that the README that used to live in the `packer/` directory has migrated to the `docs/` dir.
With that in mind, I am not entirely sure if it makes sense to have README files in the `packer` and `swizzle` directory. One idea that crossed my mind is that we could put developer-facing documentation in those READMEs. At the moment, they describe …

Introduce additional documentation and revamp README

---

ansible/pre.yml

This PR sets the `DEBIAN_FRONTEND` environment variable to `noninteractive` when installing python on the base machine.
Fixes #192

Export DEBIAN_FRONTEND=noninteractive env variable during python install

---

ansible/roles/docker/defaults/main.yml
ansible/roles/docker/meta/main.yml
ansible/roles/docker/tasks/redhat.yml

* Makes the role a bit more generic in prep for CentOS/RHEL 8, and adds Fedora compatibility.
* Version of Docker for RedHat and friends bumped to 18.09.6-3 from 5-3.
* Makes the role exportable for use via Ansible Galaxy
* Removes old LVM DirectMapper support no longer used since CentOS 7.4
Fixes #
- `1.14`
_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._
```release-note
```

Genericise OS support for Docker role

---

ansible/roles/kubernetes-cni/tasks/canal.yml

Newer versions of Canal do not include a separate RBAC manifest.
Therefore, only apply the manifest when it is defined.

Only apply the Canal RBAC when defined

---

swizzle/install.yml

This moves the installation of CNI bits to the master nodes only.
Fixes #
- `1.`
_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._
```release-note
```

Only install the CNI components on masters

---

ansible/roles/kubernetes-common/defaults/main.yml
ansible/roles/kubernetes-common/tasks/main.yml
ansible/roles/kubernetes-common/templates/etc/kubernetes/kubeadm.conf
ansible/roles/kubernetes-common/templates/var/lib/kubelet/config.yaml
ansible/roles/kubernetes-master/defaults/main.yml
ansible/roles/kubernetes-master/tasks/install.yml
ansible/roles/kubernetes-master/tasks/main.yml
ansible/roles/kubernetes-master/tasks/upgrade.yml
ansible/roles/kubernetes-master/templates/etc/kubernetes/kubeadm.conf
ansible/roles/kubernetes-node/defaults/main.yml
ansible/roles/kubernetes-node/tasks/main.yml
ansible/roles/kubernetes-node/templates/etc/kubernetes/kubeadm.conf
swizzle/upgrade.yml

This change moves the kubeadm configurations to the respective node
types. This facilitates the ability to use kubeadm for kubelet
configuration. Similarly we now make use of the kubeadm ConfigMap via
kubeadm.
Fixes #
- `1.`
_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._
```release-note
```

refactor to make use of new kubeadm capabilities
